{{- $search := .Values.search.elasticsearch | default dict -}}
{{- if $search.enabled -}}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
    name: {{ include "elasticsearch.name" . }}
    namespace: {{ .Release.Namespace }}
spec:
    http:
        tls:
            selfSignedCertificate:
                disabled: true
    nodeSets:
        -   count: {{ $search.nodeCount }}
            name: default
            podTemplate:
                spec:
                    containers:
                        -   env:
                            {{- if or $search.env $search.customEnv }}
                                {{- with $search.env }}
                                {{- toYaml . | nindent 32 }}
                                {{- end }}
                                    {{- range $k, $v := $search.customEnv }}
                                    {{- toYaml $v | nindent 32 }}
                                    {{- end }}
                                {{- else }}
                                -   name:   ES_JAVA_OPTS
                                    value: "-Xms4g -Xmx4g"
                                {{- end }}
                            name: elasticsearch
                            resources:
                                {{- if $search.resources -}}
                                {{ $search.resources | toYaml | nindent 32 }}
                                {{- else }}
                                requests:
                                    cpu: 500m
                                    memory: 4Gi
                                limits:
                                    cpu: 1000m
                                    memory: 8Gi
                            {{- end }}
                    initContainers:
                        -   command:
                                -   sh
                                -   -c
                                -   sysctl -w vm.max_map_count={{ $search.maxMapCount }}
                            name: configure-memory-map
                            securityContext:
                                privileged: true
                                runAsUser: 0
                        -   command:
                                -   sh
                                -   -c
                                -   |
                                    elasticsearch-plugin \
                                        install \
                                        --batch \
                                        analysis-{icu,kuromoji,smartcn,stempel}
                            name: install-plugins
            volumeClaimTemplates:
                -   metadata:
                        name: elasticsearch-data
                    spec:
                        accessModes:
                            -   ReadWriteOnce
                        resources:
                            requests:
                                storage: {{ $search.volumeSize }}
    version: {{ $search.version }}
---
apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-connection-details
type: Opaque
stringData:
    ELASTICSEARCH_DEFAULT_PASSWORD_SECRET_NAME: "{{ include "elasticsearch.name" . }}-es-elastic-user"
    ELASTICSEARCH_DEFAULT_USERNAME: "elastic"
    ELASTICSEARCH_URL: "http://{{ include "elasticsearch.name" . }}-es-http.{{ .Release.Namespace }}.svc:9200"
{{- end -}}