{{- $search := .Values.search -}}
{{- if $search.enabled -}}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
    name: {{ $search.name | default (printf "%s-es" .Release.Name) }}
    namespace: {{ .Release.Namespace }}
spec:
    http:
        tls:
            selfSignedCertificate:
                disabled: true
    nodeSets:
        -   count: {{ $search.nodeCount | default 3 }}
            name: default
            podTemplate:
                spec:
                    containers:
                        -   #
                            env:
                            {{- if or $search.env $search.customEnv }}
                                {{- with $search.env }}
                                {{- toYaml . | nindent 32 }}
                                {{- end }}
                                    {{- range $k, $v := $search.customEnv }}
                                    {{- toYaml $v | nindent 32 }}
                                    {{- end }}
                                {{- else }}
                                -   name:   ES_JAVA_OPTS
                                    value: "-Xms4g -Xmx4g"
                                {{- end }}
                            name: elasticsearch
                            resources:
                                {{- if $search.resources -}}
                                {{ $search.resources | toYaml | nindent 32 }}
                                {{- else }}
                                requests:
                                    cpu: 500m
                                    memory: 4Gi
                                limits:
                                    cpu: 1000m
                                    memory: 8Gi
                            {{- end }}
                    initContainers:
                        -   command:
                                -   sh
                                -   -c
                                -   sysctl -w vm.max_map_count={{ $search.maxMapCount | default 262144 }}
                            name: configure-memory-map
                            securityContext:
                                privileged: true
                                runAsUser: 0
                        -   command:
                                -   sh
                                -   -c
                                -   |
                                    elasticsearch-plugin \
                                        install \
                                        --batch \
                                        analysis-{icu,kuromoji,smartcn,stempel}
                            name: install-plugins
            volumeClaimTemplates:
                -   metadata:
                        name: elasticsearch-data
                    spec:
                        accessModes:
                            -   ReadWriteOnce
                        resources:
                            requests:
                                storage: {{ $search.volumeSize | default "10Gi" }}
    version: {{ $search.version | default "8.12.0" }}
{{- end -}}