##
## Test Suites
##

    modified.files.includes[relevant][dispatch-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**

    relevant.rule.names=dispatch-java-rule

    test.batch.names[relevant][dispatch-java-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][dispatch-java-rule]=\
        apps/dispatch/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][dispatch-java-rule]=\
        apps/dispatch/**/*Test.java

    test.batch.class.names.includes[relevant][dispatch-rule]=\
        **/dispatch/**/*Test.java

##
## Testray
##

    testray.main.component.name=Job Scheduler