#
# Application
#

liferay.customer.etc.spring.boot.client.extension.url=http://localhost:58081
liferay.customer.zendesk.ticket.closed.days=30
liferay.osb.spring.boot.client.zendesk.api.token=
liferay.osb.spring.boot.client.zendesk.api.email.address=
liferay.osb.spring.boot.client.zendesk.url=

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay-customer-etc-cron-oauth-application-headless-server.oauth2.headless.server.client.secret=secret-2db4d9e6-81c1-a1b9-aaae-f5da1c69dd
liferay-customer-etc-spring-boot-oauth-application-headless-server.oauth2.headless.server.client.secret=secret-7a56741e-7c20-e96a-36c6-81fb9b8a1ce7

liferay.oauth.application.external.reference.codes=\
    liferay-customer-etc-cron-oauth-application-headless-server,\
    liferay-customer-etc-spring-boot-oauth-application-headless-server

liferay.oauth.urls.excludes=/ready