/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UnreferencedTestEntity {
    'description'?: string;
    'id'?: number;
    'property_with_hyphens'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "property_with_hyphens",
            "baseName": "property-with-hyphens",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UnreferencedTestEntity.attributeTypeMap;
    }
}

