##
## Relevant
##

    playwright.test.project[playwright-js-tomcat90-mysql57][relevant][commerce-product-content-web-rule]=commerce-product-content-web

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][commerce-product-content-web-rule]=\
        (testray.main.component.name == "Commerce")

##
## Test Suites
##

    modified.files.includes[relevant][commerce-product-content-web-rule]=**

    relevant.rule.names=\
        commerce-product-content-web-rule

    test.batch.names[relevant][commerce-product-content-web-rule]=\
        functional-upgrade-tomcat90-mysql57,\
        playwright-js-tomcat90-mysql57

##
## Testray
##

    testray.main.component.name=Commerce