/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.IndexEntry;
import com.liferay.portal.tools.service.builder.test.service.IndexEntryLocalService;
import com.liferay.portal.tools.service.builder.test.service.IndexEntryLocalServiceUtil;
import com.liferay.portal.tools.service.builder.test.service.persistence.IndexEntryPersistence;
import com.liferay.portal.tools.service.builder.test.service.persistence.KeywordsEntryPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the index entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.IndexEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.IndexEntryLocalServiceImpl
 * @generated
 */
public abstract class IndexEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements IdentifiableOSGiService, IndexEntryLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>IndexEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>IndexEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the index entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect IndexEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param indexEntry the index entry
	 * @return the index entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public IndexEntry addIndexEntry(IndexEntry indexEntry) {
		indexEntry.setNew(true);

		return indexEntryPersistence.update(indexEntry);
	}

	/**
	 * Creates a new index entry with the primary key. Does not add the index entry to the database.
	 *
	 * @param indexEntryId the primary key for the new index entry
	 * @return the new index entry
	 */
	@Override
	@Transactional(enabled = false)
	public IndexEntry createIndexEntry(long indexEntryId) {
		return indexEntryPersistence.create(indexEntryId);
	}

	/**
	 * Deletes the index entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect IndexEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param indexEntryId the primary key of the index entry
	 * @return the index entry that was removed
	 * @throws PortalException if a index entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public IndexEntry deleteIndexEntry(long indexEntryId)
		throws PortalException {

		return indexEntryPersistence.remove(indexEntryId);
	}

	/**
	 * Deletes the index entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect IndexEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param indexEntry the index entry
	 * @return the index entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public IndexEntry deleteIndexEntry(IndexEntry indexEntry) {
		return indexEntryPersistence.remove(indexEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return indexEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			IndexEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return indexEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.IndexEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return indexEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.IndexEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return indexEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return indexEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return indexEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public IndexEntry fetchIndexEntry(long indexEntryId) {
		return indexEntryPersistence.fetchByPrimaryKey(indexEntryId);
	}

	/**
	 * Returns the index entry with the primary key.
	 *
	 * @param indexEntryId the primary key of the index entry
	 * @return the index entry
	 * @throws PortalException if a index entry with the primary key could not be found
	 */
	@Override
	public IndexEntry getIndexEntry(long indexEntryId) throws PortalException {
		return indexEntryPersistence.findByPrimaryKey(indexEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(indexEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(IndexEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("indexEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			indexEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(IndexEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"indexEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(indexEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(IndexEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("indexEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return indexEntryPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement IndexEntryLocalServiceImpl#deleteIndexEntry(IndexEntry) to avoid orphaned data");
		}

		return indexEntryLocalService.deleteIndexEntry(
			(IndexEntry)persistedModel);
	}

	@Override
	public BasePersistence<IndexEntry> getBasePersistence() {
		return indexEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return indexEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the index entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.IndexEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of index entries
	 * @param end the upper bound of the range of index entries (not inclusive)
	 * @return the range of index entries
	 */
	@Override
	public List<IndexEntry> getIndexEntries(int start, int end) {
		return indexEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of index entries.
	 *
	 * @return the number of index entries
	 */
	@Override
	public int getIndexEntriesCount() {
		return indexEntryPersistence.countAll();
	}

	/**
	 * Updates the index entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect IndexEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param indexEntry the index entry
	 * @return the index entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public IndexEntry updateIndexEntry(IndexEntry indexEntry) {
		return indexEntryPersistence.update(indexEntry);
	}

	/**
	 */
	@Override
	public boolean addKeywordsEntryIndexEntry(
		long keywordsEntryId, long indexEntryId) {

		return keywordsEntryPersistence.addIndexEntry(
			keywordsEntryId, indexEntryId);
	}

	/**
	 */
	@Override
	public boolean addKeywordsEntryIndexEntry(
		long keywordsEntryId, IndexEntry indexEntry) {

		return keywordsEntryPersistence.addIndexEntry(
			keywordsEntryId, indexEntry);
	}

	/**
	 */
	@Override
	public boolean addKeywordsEntryIndexEntries(
		long keywordsEntryId, long[] indexEntryIds) {

		return keywordsEntryPersistence.addIndexEntries(
			keywordsEntryId, indexEntryIds);
	}

	/**
	 */
	@Override
	public boolean addKeywordsEntryIndexEntries(
		long keywordsEntryId, List<IndexEntry> indexEntries) {

		return keywordsEntryPersistence.addIndexEntries(
			keywordsEntryId, indexEntries);
	}

	/**
	 */
	@Override
	public void clearKeywordsEntryIndexEntries(long keywordsEntryId) {
		keywordsEntryPersistence.clearIndexEntries(keywordsEntryId);
	}

	/**
	 */
	@Override
	public void deleteKeywordsEntryIndexEntry(
		long keywordsEntryId, long indexEntryId) {

		keywordsEntryPersistence.removeIndexEntry(
			keywordsEntryId, indexEntryId);
	}

	/**
	 */
	@Override
	public void deleteKeywordsEntryIndexEntry(
		long keywordsEntryId, IndexEntry indexEntry) {

		keywordsEntryPersistence.removeIndexEntry(keywordsEntryId, indexEntry);
	}

	/**
	 */
	@Override
	public void deleteKeywordsEntryIndexEntries(
		long keywordsEntryId, long[] indexEntryIds) {

		keywordsEntryPersistence.removeIndexEntries(
			keywordsEntryId, indexEntryIds);
	}

	/**
	 */
	@Override
	public void deleteKeywordsEntryIndexEntries(
		long keywordsEntryId, List<IndexEntry> indexEntries) {

		keywordsEntryPersistence.removeIndexEntries(
			keywordsEntryId, indexEntries);
	}

	/**
	 * Returns the keywordsEntryIds of the keywords entries associated with the index entry.
	 *
	 * @param indexEntryId the indexEntryId of the index entry
	 * @return long[] the keywordsEntryIds of keywords entries associated with the index entry
	 */
	@Override
	public long[] getKeywordsEntryPrimaryKeys(long indexEntryId) {
		return indexEntryPersistence.getKeywordsEntryPrimaryKeys(indexEntryId);
	}

	/**
	 */
	@Override
	public List<IndexEntry> getKeywordsEntryIndexEntries(long keywordsEntryId) {
		return keywordsEntryPersistence.getIndexEntries(keywordsEntryId);
	}

	/**
	 */
	@Override
	public List<IndexEntry> getKeywordsEntryIndexEntries(
		long keywordsEntryId, int start, int end) {

		return keywordsEntryPersistence.getIndexEntries(
			keywordsEntryId, start, end);
	}

	/**
	 */
	@Override
	public List<IndexEntry> getKeywordsEntryIndexEntries(
		long keywordsEntryId, int start, int end,
		OrderByComparator<IndexEntry> orderByComparator) {

		return keywordsEntryPersistence.getIndexEntries(
			keywordsEntryId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getKeywordsEntryIndexEntriesCount(long keywordsEntryId) {
		return keywordsEntryPersistence.getIndexEntriesSize(keywordsEntryId);
	}

	/**
	 */
	@Override
	public boolean hasKeywordsEntryIndexEntry(
		long keywordsEntryId, long indexEntryId) {

		return keywordsEntryPersistence.containsIndexEntry(
			keywordsEntryId, indexEntryId);
	}

	/**
	 */
	@Override
	public boolean hasKeywordsEntryIndexEntries(long keywordsEntryId) {
		return keywordsEntryPersistence.containsIndexEntries(keywordsEntryId);
	}

	/**
	 */
	@Override
	public void setKeywordsEntryIndexEntries(
		long keywordsEntryId, long[] indexEntryIds) {

		keywordsEntryPersistence.setIndexEntries(
			keywordsEntryId, indexEntryIds);
	}

	/**
	 * Returns the index entry local service.
	 *
	 * @return the index entry local service
	 */
	public IndexEntryLocalService getIndexEntryLocalService() {
		return indexEntryLocalService;
	}

	/**
	 * Sets the index entry local service.
	 *
	 * @param indexEntryLocalService the index entry local service
	 */
	public void setIndexEntryLocalService(
		IndexEntryLocalService indexEntryLocalService) {

		this.indexEntryLocalService = indexEntryLocalService;
	}

	/**
	 * Returns the index entry persistence.
	 *
	 * @return the index entry persistence
	 */
	public IndexEntryPersistence getIndexEntryPersistence() {
		return indexEntryPersistence;
	}

	/**
	 * Sets the index entry persistence.
	 *
	 * @param indexEntryPersistence the index entry persistence
	 */
	public void setIndexEntryPersistence(
		IndexEntryPersistence indexEntryPersistence) {

		this.indexEntryPersistence = indexEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		IndexEntryLocalServiceUtil.setService(indexEntryLocalService);
	}

	public void destroy() {
		IndexEntryLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return IndexEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return IndexEntry.class;
	}

	protected String getModelClassName() {
		return IndexEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = indexEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = IndexEntryLocalService.class)
	protected IndexEntryLocalService indexEntryLocalService;

	@BeanReference(type = IndexEntryPersistence.class)
	protected IndexEntryPersistence indexEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@BeanReference(type = KeywordsEntryPersistence.class)
	protected KeywordsEntryPersistence keywordsEntryPersistence;

	private static final Log _log = LogFactoryUtil.getLog(
		IndexEntryLocalServiceBaseImpl.class);

}