/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.KeywordsEntry;
import com.liferay.portal.tools.service.builder.test.service.KeywordsEntryLocalService;
import com.liferay.portal.tools.service.builder.test.service.KeywordsEntryLocalServiceUtil;
import com.liferay.portal.tools.service.builder.test.service.persistence.IndexEntryPersistence;
import com.liferay.portal.tools.service.builder.test.service.persistence.KeywordsEntryPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the keywords entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.KeywordsEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.KeywordsEntryLocalServiceImpl
 * @generated
 */
public abstract class KeywordsEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements IdentifiableOSGiService, KeywordsEntryLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>KeywordsEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>KeywordsEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the keywords entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect KeywordsEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param keywordsEntry the keywords entry
	 * @return the keywords entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public KeywordsEntry addKeywordsEntry(KeywordsEntry keywordsEntry) {
		keywordsEntry.setNew(true);

		return keywordsEntryPersistence.update(keywordsEntry);
	}

	/**
	 * Creates a new keywords entry with the primary key. Does not add the keywords entry to the database.
	 *
	 * @param keywordsEntryId the primary key for the new keywords entry
	 * @return the new keywords entry
	 */
	@Override
	@Transactional(enabled = false)
	public KeywordsEntry createKeywordsEntry(long keywordsEntryId) {
		return keywordsEntryPersistence.create(keywordsEntryId);
	}

	/**
	 * Deletes the keywords entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect KeywordsEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param keywordsEntryId the primary key of the keywords entry
	 * @return the keywords entry that was removed
	 * @throws PortalException if a keywords entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public KeywordsEntry deleteKeywordsEntry(long keywordsEntryId)
		throws PortalException {

		return keywordsEntryPersistence.remove(keywordsEntryId);
	}

	/**
	 * Deletes the keywords entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect KeywordsEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param keywordsEntry the keywords entry
	 * @return the keywords entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public KeywordsEntry deleteKeywordsEntry(KeywordsEntry keywordsEntry) {
		return keywordsEntryPersistence.remove(keywordsEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return keywordsEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			KeywordsEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return keywordsEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.KeywordsEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return keywordsEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.KeywordsEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return keywordsEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return keywordsEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return keywordsEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public KeywordsEntry fetchKeywordsEntry(long keywordsEntryId) {
		return keywordsEntryPersistence.fetchByPrimaryKey(keywordsEntryId);
	}

	/**
	 * Returns the keywords entry with the primary key.
	 *
	 * @param keywordsEntryId the primary key of the keywords entry
	 * @return the keywords entry
	 * @throws PortalException if a keywords entry with the primary key could not be found
	 */
	@Override
	public KeywordsEntry getKeywordsEntry(long keywordsEntryId)
		throws PortalException {

		return keywordsEntryPersistence.findByPrimaryKey(keywordsEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(keywordsEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(KeywordsEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("keywordsEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			keywordsEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(KeywordsEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"keywordsEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(keywordsEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(KeywordsEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("keywordsEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return keywordsEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement KeywordsEntryLocalServiceImpl#deleteKeywordsEntry(KeywordsEntry) to avoid orphaned data");
		}

		return keywordsEntryLocalService.deleteKeywordsEntry(
			(KeywordsEntry)persistedModel);
	}

	@Override
	public BasePersistence<KeywordsEntry> getBasePersistence() {
		return keywordsEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return keywordsEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the keywords entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.KeywordsEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of keywords entries
	 * @param end the upper bound of the range of keywords entries (not inclusive)
	 * @return the range of keywords entries
	 */
	@Override
	public List<KeywordsEntry> getKeywordsEntries(int start, int end) {
		return keywordsEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of keywords entries.
	 *
	 * @return the number of keywords entries
	 */
	@Override
	public int getKeywordsEntriesCount() {
		return keywordsEntryPersistence.countAll();
	}

	/**
	 * Updates the keywords entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect KeywordsEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param keywordsEntry the keywords entry
	 * @return the keywords entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public KeywordsEntry updateKeywordsEntry(KeywordsEntry keywordsEntry) {
		return keywordsEntryPersistence.update(keywordsEntry);
	}

	/**
	 */
	@Override
	public boolean addIndexEntryKeywordsEntry(
		long indexEntryId, long keywordsEntryId) {

		return indexEntryPersistence.addKeywordsEntry(
			indexEntryId, keywordsEntryId);
	}

	/**
	 */
	@Override
	public boolean addIndexEntryKeywordsEntry(
		long indexEntryId, KeywordsEntry keywordsEntry) {

		return indexEntryPersistence.addKeywordsEntry(
			indexEntryId, keywordsEntry);
	}

	/**
	 */
	@Override
	public boolean addIndexEntryKeywordsEntries(
		long indexEntryId, long[] keywordsEntryIds) {

		return indexEntryPersistence.addKeywordsEntries(
			indexEntryId, keywordsEntryIds);
	}

	/**
	 */
	@Override
	public boolean addIndexEntryKeywordsEntries(
		long indexEntryId, List<KeywordsEntry> keywordsEntries) {

		return indexEntryPersistence.addKeywordsEntries(
			indexEntryId, keywordsEntries);
	}

	/**
	 */
	@Override
	public void clearIndexEntryKeywordsEntries(long indexEntryId) {
		indexEntryPersistence.clearKeywordsEntries(indexEntryId);
	}

	/**
	 */
	@Override
	public void deleteIndexEntryKeywordsEntry(
		long indexEntryId, long keywordsEntryId) {

		indexEntryPersistence.removeKeywordsEntry(
			indexEntryId, keywordsEntryId);
	}

	/**
	 */
	@Override
	public void deleteIndexEntryKeywordsEntry(
		long indexEntryId, KeywordsEntry keywordsEntry) {

		indexEntryPersistence.removeKeywordsEntry(indexEntryId, keywordsEntry);
	}

	/**
	 */
	@Override
	public void deleteIndexEntryKeywordsEntries(
		long indexEntryId, long[] keywordsEntryIds) {

		indexEntryPersistence.removeKeywordsEntries(
			indexEntryId, keywordsEntryIds);
	}

	/**
	 */
	@Override
	public void deleteIndexEntryKeywordsEntries(
		long indexEntryId, List<KeywordsEntry> keywordsEntries) {

		indexEntryPersistence.removeKeywordsEntries(
			indexEntryId, keywordsEntries);
	}

	/**
	 * Returns the indexEntryIds of the index entries associated with the keywords entry.
	 *
	 * @param keywordsEntryId the keywordsEntryId of the keywords entry
	 * @return long[] the indexEntryIds of index entries associated with the keywords entry
	 */
	@Override
	public long[] getIndexEntryPrimaryKeys(long keywordsEntryId) {
		return keywordsEntryPersistence.getIndexEntryPrimaryKeys(
			keywordsEntryId);
	}

	/**
	 */
	@Override
	public List<KeywordsEntry> getIndexEntryKeywordsEntries(long indexEntryId) {
		return indexEntryPersistence.getKeywordsEntries(indexEntryId);
	}

	/**
	 */
	@Override
	public List<KeywordsEntry> getIndexEntryKeywordsEntries(
		long indexEntryId, int start, int end) {

		return indexEntryPersistence.getKeywordsEntries(
			indexEntryId, start, end);
	}

	/**
	 */
	@Override
	public List<KeywordsEntry> getIndexEntryKeywordsEntries(
		long indexEntryId, int start, int end,
		OrderByComparator<KeywordsEntry> orderByComparator) {

		return indexEntryPersistence.getKeywordsEntries(
			indexEntryId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getIndexEntryKeywordsEntriesCount(long indexEntryId) {
		return indexEntryPersistence.getKeywordsEntriesSize(indexEntryId);
	}

	/**
	 */
	@Override
	public boolean hasIndexEntryKeywordsEntry(
		long indexEntryId, long keywordsEntryId) {

		return indexEntryPersistence.containsKeywordsEntry(
			indexEntryId, keywordsEntryId);
	}

	/**
	 */
	@Override
	public boolean hasIndexEntryKeywordsEntries(long indexEntryId) {
		return indexEntryPersistence.containsKeywordsEntries(indexEntryId);
	}

	/**
	 */
	@Override
	public void setIndexEntryKeywordsEntries(
		long indexEntryId, long[] keywordsEntryIds) {

		indexEntryPersistence.setKeywordsEntries(
			indexEntryId, keywordsEntryIds);
	}

	/**
	 * Returns the keywords entry local service.
	 *
	 * @return the keywords entry local service
	 */
	public KeywordsEntryLocalService getKeywordsEntryLocalService() {
		return keywordsEntryLocalService;
	}

	/**
	 * Sets the keywords entry local service.
	 *
	 * @param keywordsEntryLocalService the keywords entry local service
	 */
	public void setKeywordsEntryLocalService(
		KeywordsEntryLocalService keywordsEntryLocalService) {

		this.keywordsEntryLocalService = keywordsEntryLocalService;
	}

	/**
	 * Returns the keywords entry persistence.
	 *
	 * @return the keywords entry persistence
	 */
	public KeywordsEntryPersistence getKeywordsEntryPersistence() {
		return keywordsEntryPersistence;
	}

	/**
	 * Sets the keywords entry persistence.
	 *
	 * @param keywordsEntryPersistence the keywords entry persistence
	 */
	public void setKeywordsEntryPersistence(
		KeywordsEntryPersistence keywordsEntryPersistence) {

		this.keywordsEntryPersistence = keywordsEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		KeywordsEntryLocalServiceUtil.setService(keywordsEntryLocalService);
	}

	public void destroy() {
		KeywordsEntryLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return KeywordsEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return KeywordsEntry.class;
	}

	protected String getModelClassName() {
		return KeywordsEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = keywordsEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = KeywordsEntryLocalService.class)
	protected KeywordsEntryLocalService keywordsEntryLocalService;

	@BeanReference(type = KeywordsEntryPersistence.class)
	protected KeywordsEntryPersistence keywordsEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@BeanReference(type = IndexEntryPersistence.class)
	protected IndexEntryPersistence indexEntryPersistence;

	private static final Log _log = LogFactoryUtil.getLog(
		KeywordsEntryLocalServiceBaseImpl.class);

}