##
## Test Suites
##

modified.files.includes[relevant][commerce-product-content-search-web-rule]=**

#
# Relevant
#

playwright.test.project[playwright-js-tomcat90-mysql57][relevant][commerce-product-content-search-web-rule]=commerce-product-content-search-web

relevant.rule.names=\
    commerce-product-content-search-web-rule

test.batch.names[relevant][commerce-product-content-search-web-rule]=\
    playwright-js-tomcat90-mysql57