/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the IndexEntry service. Represents a row in the &quot;IndexEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.IndexEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.IndexEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see IndexEntry
 * @generated
 */
@ProviderType
public interface IndexEntryModel extends BaseModel<IndexEntry>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a index entry model instance should use the {@link IndexEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this index entry.
	 *
	 * @return the primary key of this index entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this index entry.
	 *
	 * @param primaryKey the primary key of this index entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the index entry ID of this index entry.
	 *
	 * @return the index entry ID of this index entry
	 */
	public long getIndexEntryId();

	/**
	 * Sets the index entry ID of this index entry.
	 *
	 * @param indexEntryId the index entry ID of this index entry
	 */
	public void setIndexEntryId(long indexEntryId);

	/**
	 * Returns the company ID of this index entry.
	 *
	 * @return the company ID of this index entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this index entry.
	 *
	 * @param companyId the company ID of this index entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this index entry.
	 *
	 * @return the name of this index entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this index entry.
	 *
	 * @param name the name of this index entry
	 */
	public void setName(String name);

	@Override
	public IndexEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}