/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the KeywordsEntry service. Represents a row in the &quot;KeywordsEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.KeywordsEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.KeywordsEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see KeywordsEntry
 * @generated
 */
@ProviderType
public interface KeywordsEntryModel
	extends BaseModel<KeywordsEntry>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a keywords entry model instance should use the {@link KeywordsEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this keywords entry.
	 *
	 * @return the primary key of this keywords entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this keywords entry.
	 *
	 * @param primaryKey the primary key of this keywords entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the keywords entry ID of this keywords entry.
	 *
	 * @return the keywords entry ID of this keywords entry
	 */
	public long getKeywordsEntryId();

	/**
	 * Sets the keywords entry ID of this keywords entry.
	 *
	 * @param keywordsEntryId the keywords entry ID of this keywords entry
	 */
	public void setKeywordsEntryId(long keywordsEntryId);

	/**
	 * Returns the company ID of this keywords entry.
	 *
	 * @return the company ID of this keywords entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this keywords entry.
	 *
	 * @param companyId the company ID of this keywords entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this keywords entry.
	 *
	 * @return the name of this keywords entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this keywords entry.
	 *
	 * @param name the name of this keywords entry
	 */
	public void setName(String name);

	@Override
	public KeywordsEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}