/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.kernel.dao.db;

import com.liferay.portal.kernel.dao.jdbc.util.CallableStatementWrapper;
import com.liferay.portal.kernel.dao.jdbc.util.ConnectionWrapper;
import com.liferay.portal.kernel.dao.jdbc.util.PreparedStatementWrapper;
import com.liferay.portal.kernel.dao.jdbc.util.StatementWrapper;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.ArrayList;
import java.util.List;

/**
 * @author István András Dézsi
 */
public class SQLStatementRecorder {

	public static Connection getConnectionWrapper(Connection connection) {
		if (!_enabled) {
			return connection;
		}

		return new ConnectionWrapper(connection) {

			@Override
			public Statement createStatement() throws SQLException {
				return _wrapStatement(super.createStatement());
			}

			@Override
			public Statement createStatement(
					int resultSetType, int resultSetConcurrency)
				throws SQLException {

				return _wrapStatement(
					super.createStatement(resultSetType, resultSetConcurrency));
			}

			@Override
			public Statement createStatement(
					int resultSetType, int resultSetConcurrency,
					int resultSetHoldability)
				throws SQLException {

				return _wrapStatement(
					super.createStatement(
						resultSetType, resultSetConcurrency,
						resultSetHoldability));
			}

			@Override
			public CallableStatement prepareCall(String sql)
				throws SQLException {

				return (CallableStatement)_wrapStatement(
					super.prepareCall(sql));
			}

			@Override
			public CallableStatement prepareCall(
					String sql, int resultSetType, int resultSetConcurrency)
				throws SQLException {

				return (CallableStatement)_wrapStatement(
					super.prepareCall(
						sql, resultSetType, resultSetConcurrency));
			}

			@Override
			public CallableStatement prepareCall(
					String sql, int resultSetType, int resultSetConcurrency,
					int resultSetHoldability)
				throws SQLException {

				return (CallableStatement)_wrapStatement(
					super.prepareCall(
						sql, resultSetType, resultSetConcurrency,
						resultSetHoldability));
			}

			@Override
			public PreparedStatement prepareStatement(String sql)
				throws SQLException {

				return (PreparedStatement)_wrapStatement(
					super.prepareStatement(sql));
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int autoGeneratedKeys)
				throws SQLException {

				return (PreparedStatement)_wrapStatement(
					super.prepareStatement(sql, autoGeneratedKeys));
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int resultSetType, int resultSetConcurrency)
				throws SQLException {

				return (PreparedStatement)_wrapStatement(
					super.prepareStatement(
						sql, resultSetType, resultSetConcurrency));
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int resultSetType, int resultSetConcurrency,
					int resultSetHoldability)
				throws SQLException {

				return (PreparedStatement)_wrapStatement(
					super.prepareStatement(
						sql, resultSetType, resultSetConcurrency,
						resultSetHoldability));
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, int[] columnIndexes)
				throws SQLException {

				return (PreparedStatement)_wrapStatement(
					super.prepareStatement(sql, columnIndexes));
			}

			@Override
			public PreparedStatement prepareStatement(
					String sql, String[] columnNames)
				throws SQLException {

				return (PreparedStatement)_wrapStatement(
					super.prepareStatement(sql, columnNames));
			}

		};
	}

	public static List<String> getFailedSQLStatements() {
		return _failedSQLStatements;
	}

	public static void start() {
		_failedSQLStatements.clear();

		_enabled = true;
	}

	public static void stop() {
		_enabled = false;
	}

	private static <T> T _execute(SqlCallable<T> callable, Object object)
		throws SQLException {

		try {
			return callable.call();
		}
		catch (SQLException sqlException) {
			String sql = _extractSqlStatement(object);

			if (sql != null) {
				String message = sqlException.getMessage();

				if (Validator.isBlank(message)) {
					_failedSQLStatements.add("SQL: " + sql);
				}
				else {
					_failedSQLStatements.add(
						StringBundler.concat(
							"SQL: ", sql, ";\tError: ", message));
				}
			}

			throw sqlException;
		}
	}

	private static String _extractSqlStatement(Object object) {
		if (object instanceof String) {
			return (String)object;
		}
		else if (object instanceof Statement) {
			String statementString = object.toString();

			int colonIndex = statementString.indexOf(':');

			if (colonIndex >= 0) {
				return statementString.substring(
					colonIndex + 1
				).trim();
			}
		}

		return null;
	}

	private static <T extends Statement> T _wrapStatement(T statement) {
		if (statement instanceof CallableStatement) {
			return (T)new CallableStatementWrapper(
				(CallableStatement)statement) {

				@Override
				public boolean execute() throws SQLException {
					return _execute(() -> super.execute(), statement);
				}

				@Override
				public int[] executeBatch() throws SQLException {
					return _execute(() -> super.executeBatch(), statement);
				}

				@Override
				public ResultSet executeQuery() throws SQLException {
					return _execute(() -> super.executeQuery(), statement);
				}

				@Override
				public int executeUpdate() throws SQLException {
					return _execute(() -> super.executeUpdate(), statement);
				}

			};
		}
		else if (statement instanceof PreparedStatement) {
			return (T)new PreparedStatementWrapper(
				(PreparedStatement)statement) {

				@Override
				public boolean execute() throws SQLException {
					return _execute(() -> super.execute(), statement);
				}

				@Override
				public int[] executeBatch() throws SQLException {
					return _execute(() -> super.executeBatch(), statement);
				}

				@Override
				public ResultSet executeQuery() throws SQLException {
					return _execute(() -> super.executeQuery(), statement);
				}

				@Override
				public int executeUpdate() throws SQLException {
					return _execute(() -> super.executeUpdate(), statement);
				}

			};
		}

		return (T)new StatementWrapper(statement) {

			@Override
			public boolean execute(String sql) throws SQLException {
				return _execute(() -> super.execute(sql), sql);
			}

			@Override
			public int[] executeBatch() throws SQLException {
				return _execute(() -> super.executeBatch(), statement);
			}

			@Override
			public ResultSet executeQuery(String sql) throws SQLException {
				return _execute(() -> super.executeQuery(sql), sql);
			}

			@Override
			public int executeUpdate(String sql) throws SQLException {
				return _execute(() -> super.executeUpdate(sql), sql);
			}

			@Override
			public boolean execute(String sql, int autoGeneratedKeys)
				throws SQLException {

				return _execute(
					() -> super.execute(sql, autoGeneratedKeys), sql);
			}

			@Override
			public boolean execute(String sql, int[] columnIndexes)
				throws SQLException {

				return _execute(() -> super.execute(sql, columnIndexes), sql);
			}

			@Override
			public boolean execute(String sql, String[] columnNames)
				throws SQLException {

				return _execute(() -> super.execute(sql, columnNames), sql);
			}

			@Override
			public int executeUpdate(String sql, int autoGeneratedKeys)
				throws SQLException {

				return _execute(
					() -> super.executeUpdate(sql, autoGeneratedKeys), sql);
			}

			@Override
			public int executeUpdate(String sql, int[] columnIndexes)
				throws SQLException {

				return _execute(
					() -> super.executeUpdate(sql, columnIndexes), sql);
			}

			@Override
			public int executeUpdate(String sql, String[] columnNames)
				throws SQLException {

				return _execute(
					() -> super.executeUpdate(sql, columnNames), sql);
			}

		};
	}

	private static boolean _enabled;
	private static final List<String> _failedSQLStatements = new ArrayList<>();

	@FunctionalInterface
	private interface SqlCallable<R> {

		public R call() throws SQLException;

	}

}