/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

import {expect, mergeTests} from '@playwright/test';

import {partnerHelper} from '../fixtures/partnerHelper';
import {partnerPagesTest} from '../fixtures/partnerPages';
import {partnerSiteFixture} from '../fixtures/partnerSite';
import {customFormatDate} from '../utils/customFormatDate';
import getDateCustomFormat from '../utils/getFormatDate';
import {mockMDFRequestData} from '../utils/mockData';

export const test = mergeTests(partnerHelper, partnerSiteFixture, partnerPagesTest);

test.describe('MDF Request Page', () => {
	const accountName = 'Deathray, Inc.*';
	const accountRole = '[Account] Partner Manager (PM)';

	let accountUser;
	let autoGenerateData;
	let formatEndDate;
	let formatStartDate;
	let mdfRequestData;

	test.beforeEach(async ({partnerHelper, partnerMDFListPage}) => {
		const { account } = await partnerHelper.createAccountUser({accountName, accountType: 'business'});
		await partnerHelper.assignUserToAccountRole({accountId: account.id, accountRole});

		accountUser = account;

		mdfRequestData = await partnerHelper.createMDFRequest({
			data: mockMDFRequestData
		});

		await partnerMDFListPage.goto();

		autoGenerateData = await partnerMDFListPage.getGeneratedDataFromRequest(
			mdfRequestData.overallCampaignName
		);

		formatEndDate = getDateCustomFormat(
			mdfRequestData.maxDateActivity,
			customFormatDate.SHORT_MONTH
		);
		formatStartDate = getDateCustomFormat(
			mdfRequestData.minDateActivity,
			customFormatDate.SHORT_MONTH
		);
	});

	test.afterEach(async ({apiHelpers}) => {
		await apiHelpers.headlessAdminUser.deleteAccount(accountUser.id);

		await apiHelpers.delete(`/o/c/mdfrequests/${mdfRequestData.id}`);
	})

	test('Should display MDF Resquest List', async ({partnerMDFListPage}) => {
		const campaignName = await partnerMDFListPage.getCampaignName();
		const endActPeriod =
			await partnerMDFListPage.getEndActPeriod(formatEndDate);
		const partnerName = await partnerMDFListPage.getPartnerName(
			mdfRequestData.companyName
		);
		const requested = await partnerMDFListPage.getRequested(
			mdfRequestData.totalMDFRequestAmount
		);
		const startActPeriod =
			await partnerMDFListPage.getStartActPeriod(formatStartDate);

		await expect(campaignName).toBeVisible();
		await expect(autoGenerateData.claimed).toBeTruthy();
		await expect(endActPeriod).toBeVisible();
		await expect(partnerName).toBeVisible();
		await expect(requested).toBeTruthy();
		await expect(autoGenerateData.requestId).toBeTruthy();
		await expect(startActPeriod).toBeVisible();
		await expect(autoGenerateData.status).toBeTruthy();
		await expect(autoGenerateData.submitDate).toBeTruthy();
	});

	test('Should filter data by Activity Period', async ({
		page,
		partnerMDFListPage,
	}) => {
		const endActPeriod =
			await partnerMDFListPage.getEndActPeriod(formatEndDate);
		const startActPeriod =
			await partnerMDFListPage.getStartActPeriod(formatStartDate);

		await partnerMDFListPage.filterMDFRequestByPeriod(
			'2024-07-11',
			'2024-07-12'
		);

		await page.getByText('MDF Requests').click();

		await expect(endActPeriod).toBeVisible();
		await expect(startActPeriod).toBeVisible();

		await partnerMDFListPage.clearAllFilters.click();
		await partnerMDFListPage.filterButton.click();

		await partnerMDFListPage.activityAfterDateInput.fill('2024-08-09');
		await partnerMDFListPage.activityBeforeDateInput.fill('2024-08-10');

		await partnerMDFListPage.applyFilterButton.click();
		await page.getByText('MDF Requests').click();

		await expect(partnerMDFListPage.noEntriesFoundMessage).toBeVisible();
		await expect(endActPeriod).not.toBeVisible();
		await expect(startActPeriod).not.toBeVisible();
	});

	test('Should filter data by Status', async ({page, partnerMDFListPage}) => {
		const status = autoGenerateData.status;

		await partnerMDFListPage.filterMDFRequestByStatus(status);

		await partnerMDFListPage.mdfRequestHeading.click();

		await expect(status).toBeTruthy();

		await partnerMDFListPage.clearAllFilters.click();
		await partnerMDFListPage.filterButton.click();

		await page.getByLabel('Draft').check();

		await partnerMDFListPage.applyFilterButton.click();
		await partnerMDFListPage.mdfRequestHeading.click();

		await expect(partnerMDFListPage.noEntriesFoundMessage).toBeVisible();
	});

	test('Should filter data by Partner', async ({
		page,
		partnerHelper,
		partnerMDFListPage,
	}) => {
		const { account } = await partnerHelper.createAccountUser({accountName: 'Company Name 3', accountType: 'business'});
		await partnerHelper.assignUserToAccountRole({accountId: account.id, accountRole});

		const partnerName = await partnerMDFListPage.getPartnerName(
			mdfRequestData.companyName
		);

		await partnerMDFListPage.filterMDFRequestByPartner(
			mdfRequestData.companyName
		);

		await page.getByText('MDF Requests').click();

		await expect(partnerName).toBeVisible();

		await partnerMDFListPage.clearAllFilters.click();
		await partnerMDFListPage.filterButton.click();

		await page.getByLabel('Company Name 3').check();

		await partnerMDFListPage.applyFilterButton.click();
		await page.getByText('MDF Requests').click();

		await expect(partnerMDFListPage.noEntriesFoundMessage).toBeVisible();
	});

	test('Should clean date filter fields when click on Clear All Filters', async ({
		partnerMDFListPage,
	}) => {
		await partnerMDFListPage.filterMDFRequestByPeriod(
			'2024-06-01',
			'2024-06-08'
		);

		await partnerMDFListPage.clearAllFilters.click();
		await partnerMDFListPage.filterButton.click();

		await expect(partnerMDFListPage.activityAfterDateInput).toBeEmpty();
		await expect(partnerMDFListPage.activityBeforeDateInput).toBeEmpty();
	});

	test('Should Download MDF Report', async ({page, partnerMDFListPage}) => {
		const downloadPromise = page.waitForEvent('download');
		await partnerMDFListPage.exportRequestButton.click();

		const downloadMDFReport = await downloadPromise;

		await downloadMDFReport.saveAs(
			'~/' + downloadMDFReport.suggestedFilename()
		);
		expect(downloadMDFReport.suggestedFilename()).toBe('MDF Requests.csv');
	});

	test('Should Change MDF Request Status', async ({
		partnerMDFListPage,
		partnerMDFRequestForm,
	}) => {
		const requestId = await partnerMDFListPage.getRequestId(
			autoGenerateData.requestId
		);

		await requestId.click();

		await partnerMDFRequestForm.statusDropdown.click();
		await partnerMDFRequestForm.statusDropDownOption('Approved');

		await partnerMDFRequestForm.backButton.click();

		await expect(partnerMDFListPage.getStatus('Approved')).toBeTruthy();
	});

	test('Should Find a Request using the search input', async ({
		partnerMDFListPage,
	}) => {
		const campaignName = await partnerMDFListPage.getCampaignName();
		const cleanSearch = await partnerMDFListPage.cleanSearch;

		await partnerMDFListPage.filterUsingSearchInput('Test Campaign');

		await expect(campaignName).toBeVisible();

		await cleanSearch.click();
		await partnerMDFListPage.filterUsingSearchInput('Name');

		await expect(partnerMDFListPage.noEntriesFoundMessage).toBeVisible();
	});

	test('Should Complete A MDF Request through action button', async ({
		page,
		partnerMDFListPage,
		partnerMDFRequestForm
	}) => {
		const actionButton = await partnerMDFListPage.actionButton;
		const completedTab = await partnerMDFListPage.completedTab;
		const completeMenuItem = await partnerMDFListPage.completeMenuItem;
		const requestId = await partnerMDFListPage.getRequestId(
			autoGenerateData.requestId
		);
		const successTooltip = await page.getByText('Success:MDF Request successfully completed!');

		await requestId.click();

		await partnerMDFRequestForm.statusDropdown.click();
		await partnerMDFRequestForm.statusDropDownOption('Approved');

		await partnerMDFRequestForm.backButton.click();

		await page.once('dialog', async (dialog) => {
			expect(dialog.message()).toContain('Are you sure you want to complete the MDF request?');
			await dialog.accept();
		});

		await actionButton.click();
		await completeMenuItem.click();

		await expect(successTooltip).toBeVisible();

		await completedTab.click();

		await expect(requestId).toBeVisible();
	});
});
