/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.model.IndexEntry;
import com.liferay.portal.tools.service.builder.test.model.IndexEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the IndexEntry service. Represents a row in the &quot;IndexEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>IndexEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link IndexEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see IndexEntryImpl
 * @generated
 */
public class IndexEntryModelImpl
	extends BaseModelImpl<IndexEntry> implements IndexEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a index entry model instance should use the <code>IndexEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "IndexEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"indexEntryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("indexEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table IndexEntry (indexEntryId LONG not null primary key,companyId LONG,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table IndexEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY indexEntry.indexEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY IndexEntry.indexEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long INDEXENTRYID_COLUMN_BITMASK = 1L;

	public static final String MAPPING_TABLE_INDEXENTRIES_KEYWORDSENTRIES_NAME =
		"IndexEntries_KeywordsEntries";

	public static final Object[][]
		MAPPING_TABLE_INDEXENTRIES_KEYWORDSENTRIES_COLUMNS = {
			{"companyId", Types.BIGINT}, {"indexEntryId", Types.BIGINT},
			{"keywordsEntryId", Types.BIGINT}
		};

	public static final String
		MAPPING_TABLE_INDEXENTRIES_KEYWORDSENTRIES_SQL_CREATE =
			"create table IndexEntries_KeywordsEntries (companyId LONG not null,indexEntryId LONG not null,keywordsEntryId LONG not null,primary key (indexEntryId, keywordsEntryId))";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean
		FINDER_CACHE_ENABLED_INDEXENTRIES_KEYWORDSENTRIES = true;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.IndexEntry"));

	public IndexEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _indexEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIndexEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _indexEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return IndexEntry.class;
	}

	@Override
	public String getModelClassName() {
		return IndexEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<IndexEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<IndexEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<IndexEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((IndexEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<IndexEntry, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<IndexEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(IndexEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<IndexEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<IndexEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<IndexEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<IndexEntry, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<IndexEntry, Object>>();

			attributeGetterFunctions.put(
				"indexEntryId", IndexEntry::getIndexEntryId);
			attributeGetterFunctions.put("companyId", IndexEntry::getCompanyId);
			attributeGetterFunctions.put("name", IndexEntry::getName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<IndexEntry, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<IndexEntry, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<IndexEntry, ?>>();

			attributeSetterBiConsumers.put(
				"indexEntryId",
				(BiConsumer<IndexEntry, Long>)IndexEntry::setIndexEntryId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<IndexEntry, Long>)IndexEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"name", (BiConsumer<IndexEntry, String>)IndexEntry::setName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getIndexEntryId() {
		return _indexEntryId;
	}

	@Override
	public void setIndexEntryId(long indexEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_indexEntryId = indexEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), IndexEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public IndexEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, IndexEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		IndexEntryImpl indexEntryImpl = new IndexEntryImpl();

		indexEntryImpl.setIndexEntryId(getIndexEntryId());
		indexEntryImpl.setCompanyId(getCompanyId());
		indexEntryImpl.setName(getName());

		indexEntryImpl.resetOriginalValues();

		return indexEntryImpl;
	}

	@Override
	public IndexEntry cloneWithOriginalValues() {
		IndexEntryImpl indexEntryImpl = new IndexEntryImpl();

		indexEntryImpl.setIndexEntryId(
			this.<Long>getColumnOriginalValue("indexEntryId"));
		indexEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		indexEntryImpl.setName(this.<String>getColumnOriginalValue("name"));

		return indexEntryImpl;
	}

	@Override
	public int compareTo(IndexEntry indexEntry) {
		long primaryKey = indexEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof IndexEntry)) {
			return false;
		}

		IndexEntry indexEntry = (IndexEntry)object;

		long primaryKey = indexEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<IndexEntry> toCacheModel() {
		IndexEntryCacheModel indexEntryCacheModel = new IndexEntryCacheModel();

		indexEntryCacheModel.indexEntryId = getIndexEntryId();

		indexEntryCacheModel.companyId = getCompanyId();

		indexEntryCacheModel.name = getName();

		String name = indexEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			indexEntryCacheModel.name = null;
		}

		return indexEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<IndexEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<IndexEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<IndexEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((IndexEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, IndexEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					IndexEntry.class, ModelWrapper.class);

	}

	private long _indexEntryId;
	private long _companyId;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		Function<IndexEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((IndexEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("indexEntryId", _indexEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("name", _name);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("indexEntryId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("name", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private IndexEntry _escapedModel;

}