/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.tools.service.builder.test.model.KeywordsEntry;
import com.liferay.portal.tools.service.builder.test.model.KeywordsEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the KeywordsEntry service. Represents a row in the &quot;KeywordsEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>KeywordsEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link KeywordsEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see KeywordsEntryImpl
 * @generated
 */
public class KeywordsEntryModelImpl
	extends BaseModelImpl<KeywordsEntry> implements KeywordsEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a keywords entry model instance should use the <code>KeywordsEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "KeywordsEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"keywordsEntryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("keywordsEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table KeywordsEntry (keywordsEntryId LONG not null primary key,companyId LONG,name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table KeywordsEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY keywordsEntry.keywordsEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY KeywordsEntry.keywordsEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long KEYWORDSENTRYID_COLUMN_BITMASK = 1L;

	public static final String MAPPING_TABLE_INDEXENTRIES_KEYWORDSENTRIES_NAME =
		"IndexEntries_KeywordsEntries";

	public static final Object[][]
		MAPPING_TABLE_INDEXENTRIES_KEYWORDSENTRIES_COLUMNS = {
			{"companyId", Types.BIGINT}, {"indexEntryId", Types.BIGINT},
			{"keywordsEntryId", Types.BIGINT}
		};

	public static final String
		MAPPING_TABLE_INDEXENTRIES_KEYWORDSENTRIES_SQL_CREATE =
			"create table IndexEntries_KeywordsEntries (companyId LONG not null,indexEntryId LONG not null,keywordsEntryId LONG not null,primary key (indexEntryId, keywordsEntryId))";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean
		FINDER_CACHE_ENABLED_INDEXENTRIES_KEYWORDSENTRIES = true;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.KeywordsEntry"));

	public KeywordsEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _keywordsEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setKeywordsEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _keywordsEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return KeywordsEntry.class;
	}

	@Override
	public String getModelClassName() {
		return KeywordsEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<KeywordsEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<KeywordsEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<KeywordsEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((KeywordsEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<KeywordsEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<KeywordsEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(KeywordsEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<KeywordsEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<KeywordsEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<KeywordsEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<KeywordsEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<KeywordsEntry, Object>>();

			attributeGetterFunctions.put(
				"keywordsEntryId", KeywordsEntry::getKeywordsEntryId);
			attributeGetterFunctions.put(
				"companyId", KeywordsEntry::getCompanyId);
			attributeGetterFunctions.put("name", KeywordsEntry::getName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<KeywordsEntry, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<KeywordsEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<KeywordsEntry, ?>>();

			attributeSetterBiConsumers.put(
				"keywordsEntryId",
				(BiConsumer<KeywordsEntry, Long>)
					KeywordsEntry::setKeywordsEntryId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<KeywordsEntry, Long>)KeywordsEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<KeywordsEntry, String>)KeywordsEntry::setName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getKeywordsEntryId() {
		return _keywordsEntryId;
	}

	@Override
	public void setKeywordsEntryId(long keywordsEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_keywordsEntryId = keywordsEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), KeywordsEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public KeywordsEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, KeywordsEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		KeywordsEntryImpl keywordsEntryImpl = new KeywordsEntryImpl();

		keywordsEntryImpl.setKeywordsEntryId(getKeywordsEntryId());
		keywordsEntryImpl.setCompanyId(getCompanyId());
		keywordsEntryImpl.setName(getName());

		keywordsEntryImpl.resetOriginalValues();

		return keywordsEntryImpl;
	}

	@Override
	public KeywordsEntry cloneWithOriginalValues() {
		KeywordsEntryImpl keywordsEntryImpl = new KeywordsEntryImpl();

		keywordsEntryImpl.setKeywordsEntryId(
			this.<Long>getColumnOriginalValue("keywordsEntryId"));
		keywordsEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		keywordsEntryImpl.setName(this.<String>getColumnOriginalValue("name"));

		return keywordsEntryImpl;
	}

	@Override
	public int compareTo(KeywordsEntry keywordsEntry) {
		long primaryKey = keywordsEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof KeywordsEntry)) {
			return false;
		}

		KeywordsEntry keywordsEntry = (KeywordsEntry)object;

		long primaryKey = keywordsEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<KeywordsEntry> toCacheModel() {
		KeywordsEntryCacheModel keywordsEntryCacheModel =
			new KeywordsEntryCacheModel();

		keywordsEntryCacheModel.keywordsEntryId = getKeywordsEntryId();

		keywordsEntryCacheModel.companyId = getCompanyId();

		keywordsEntryCacheModel.name = getName();

		String name = keywordsEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			keywordsEntryCacheModel.name = null;
		}

		return keywordsEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<KeywordsEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<KeywordsEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<KeywordsEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((KeywordsEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, KeywordsEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					KeywordsEntry.class, ModelWrapper.class);

	}

	private long _keywordsEntryId;
	private long _companyId;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		Function<KeywordsEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((KeywordsEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("keywordsEntryId", _keywordsEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("name", _name);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("keywordsEntryId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("name", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private KeywordsEntry _escapedModel;

}