##
## Test Suites
##

modified.files.includes[relevant][address-web-playwright-rule]=**

#
# Relevant
#

playwright.test.project[playwright-js-tomcat90-mysql57][relevant][address-web-playwright-rule]=address-web

relevant.rule.names=\
    address-web-playwright-rule

test.batch.names[relevant][address-web-playwright-rule]=\
    playwright-js-tomcat90-mysql57