defaults:
    run:
        shell: bash
env:
    ECR_REGISTRY: 709825985650.dkr.ecr.us-east-1.amazonaws.com
    GAR_REGISTRY: us-central1-docker.pkg.dev/liferay-artifact-registry/liferay-helm-chart
jobs:
    publish-aws:
        env:
            CHART_VERSION_AWS: 0.0.0
        if: ${{ github.repository == 'liferay/liferay-portal' }}
        needs: publish-default
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   env:
                    GITHUB_TOKEN: ${{ github.token }}
                id: verify_version
                name: Verify Helm chart version
                run: |
                    CHART_VERSION_AWS=$(cat ./Chart.yaml | yq .version)

                    echo "Verifying Helm chart version ${CHART_VERSION_AWS}."

                    if ! helm show readme "oci://${GAR_REGISTRY}/liferay-aws:${CHART_VERSION_AWS}" >/dev/null 2>&1
                    then
                        echo "Verified Helm Chart version ${CHART_VERSION_AWS}."

                        echo "CHART_VERSION_AWS=${CHART_VERSION_AWS}" >> ${GITHUB_ENV}

                        echo "should_publish=true" >> ${GITHUB_OUTPUT}
                    else
                        echo "Chart version ${CHART_VERSION_AWS} already exists. Skipping publish."
                    fi
                working-directory: ./cloud/helm/aws
            -   if: ${{ steps.verify_version.outputs.should_publish == 'true' }}
                name: Log in to GAR
                run: echo "${{ secrets.GAR_PASSWORD }}" | helm registry login ${GAR_REGISTRY} --password-stdin --username _json_key_base64
            -   if: ${{ steps.verify_version.outputs.should_publish == 'true' }}
                name: Package and push Helm chart
                run: |
                    DIST_DIR="${{ runner.temp }}/aws/dist"

                    rm -rf "${DIST_DIR}"

                    mkdir --parents "${DIST_DIR}"

                    helm dependency update

                    helm package . \
                        --destination "${DIST_DIR}" \
                        --version "${CHART_VERSION_AWS}"

                    for file_name in ${DIST_DIR}/*.tgz
                    do
                        echo "Pushing ${file_name}."

                        helm push "${file_name}" "oci://${GAR_REGISTRY}"
                    done
                working-directory: ./cloud/helm/aws
    publish-aws-marketplace:
        env:
            CHART_VERSION_AWS_MARKETPLACE: 0.0.0
        if: ${{ github.repository == 'liferay/liferay-portal' }}
        needs: [
            publish-aws,
            publish-default,
        ]
        runs-on: ubuntu-latest
        steps:
            -   name: Configure AWS credentials
                uses: aws-actions/configure-aws-credentials@v5.1.0
                with:
                    aws-region: us-east-1
                    role-session-name: GitHubActions
                    role-to-assume: arn:aws:iam::831926597587:role/GitHubActionsRole
            -   name: Log in to ECR
                run: |
                    aws ecr get-login-password --region us-east-1 \
                        | helm registry login "${ECR_REGISTRY}" --password-stdin --username AWS
            -   name: Checkout code
                uses: actions/checkout@v4
            -   env:
                    GITHUB_TOKEN: ${{ github.token }}
                id: verify_version
                name: Verify Helm chart version
                run: |
                    CHART_VERSION_AWS_MARKETPLACE=$(cat ./Chart.yaml | yq .version)

                    echo "Verifying Helm chart version ${CHART_VERSION_AWS_MARKETPLACE}."

                    if ! helm show readme "oci://${ECR_REGISTRY}/liferay/liferay-aws-marketplace:${CHART_VERSION_AWS_MARKETPLACE}" >/dev/null 2>&1
                    then
                        echo "Verified Helm Chart version ${CHART_VERSION_AWS_MARKETPLACE}."

                        echo "CHART_VERSION_AWS_MARKETPLACE=${CHART_VERSION_AWS_MARKETPLACE}" >> ${GITHUB_ENV}

                        echo "should_publish=true" >> ${GITHUB_OUTPUT}
                    else
                        echo "Chart version ${CHART_VERSION_AWS_MARKETPLACE} already exists. Skipping publish."
                    fi
                working-directory: ./cloud/helm/aws-marketplace
            -   if: ${{ steps.verify_version.outputs.should_publish == 'true' }}
                name: Package and push Helm chart
                run: |
                    mkdir "${{ runner.temp }}/dist"

                    helm dependency update

                    helm package . \
                        --destination "${{ runner.temp }}/dist" \
                        --version "${CHART_VERSION_AWS_MARKETPLACE}"

                    for file_name in ${{ runner.temp }}/dist/*.tgz
                    do
                        echo "Pushing ${file_name}."

                        helm push "${file_name}" "oci://${ECR_REGISTRY}/liferay"
                    done
                working-directory: ./cloud/helm/aws-marketplace
    publish-default:
        env:
            CHART_VERSION_DEFAULT: 0.0.0
        if: ${{ github.repository == 'liferay/liferay-portal' }}
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   env:
                    GITHUB_TOKEN: ${{ github.token }}
                id: verify_version
                name: Verify Helm chart version
                run: |
                    CHART_VERSION_DEFAULT=$(cat ./Chart.yaml | yq .version)

                    echo "Verifying Helm chart version ${CHART_VERSION_DEFAULT}."

                    if ! helm show readme "oci://${GAR_REGISTRY}/liferay-default:${CHART_VERSION_DEFAULT}" >/dev/null 2>&1
                    then
                        echo "Verified Helm Chart version ${CHART_VERSION_DEFAULT}."

                        echo "CHART_VERSION_DEFAULT=${CHART_VERSION_DEFAULT}" >> ${GITHUB_ENV}

                        echo "should_publish=true" >> ${GITHUB_OUTPUT}
                    else
                        echo "Chart version ${CHART_VERSION_DEFAULT} already exists. Skipping publish."
                    fi
                working-directory: ./cloud/helm/default
            -   if: ${{ steps.verify_version.outputs.should_publish == 'true' }}
                name: Log in to GAR
                run: echo "${{ secrets.GAR_PASSWORD }}" | helm registry login ${GAR_REGISTRY} --password-stdin --username _json_key_base64
            -   if: ${{ steps.verify_version.outputs.should_publish == 'true' }}
                name: Package and push Helm chart
                run: |
                    DIST_DIR="${{ runner.temp }}/default/dist"

                    rm -rf "${DIST_DIR}"

                    mkdir --parents "${DIST_DIR}"

                    helm dependency update

                    helm package . \
                        --destination "${DIST_DIR}" \
                        --version "${CHART_VERSION_DEFAULT}"

                    for file_name in ${DIST_DIR}/*.tgz
                    do
                        echo "Pushing ${file_name}."

                        helm push "${file_name}" "oci://${GAR_REGISTRY}"
                    done
                working-directory: ./cloud/helm/default
on:
    push:
        branches:
            -   master
        paths:
            -   cloud/helm/**
permissions:
    id-token: write